#!/bin/bash

# Manual Upload Instructions for Project Phantasia
echo "🚀 Project Phantasia Deployment Instructions"
echo "==========================================="
echo ""
echo "1. Upload files to server:"
echo "   scp -P 22 phantasia-deploy.tar.gz root@212.227.85.148:~/"
echo "   scp -P 22 server_setup.sh root@212.227.85.148:~/"
echo ""
echo "   Password: voan6B86"
echo ""
echo "2. Connect to server:"
echo "   ssh -p 22 root@212.227.85.148"
echo ""
echo "3. Run setup on server:"
echo "   chmod +x server_setup.sh"
echo "   ./server_setup.sh"
echo ""
echo "Files ready for upload:"
ls -la phantasia-deploy.tar.gz server_setup.sh 2>/dev/null | grep -E "\.(tar\.gz|sh)$"
echo ""
echo "Server IP: 212.227.85.148"
echo "Username: root" 
echo "Password: voan6B86"