# Logstash configuration for processing logs

http.host: "0.0.0.0"
xpack.monitoring.enabled: false
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Pipeline configuration
path.config: /usr/share/logstash/pipeline
config.reload.automatic: true
config.reload.interval: 3s

# Performance tuning
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Queue settings
queue.type: persisted
queue.max_bytes: 1gb